class USCourtList():
    
    """
    
    This class stores the list of US courts and their webpages, including:
    1. 13 US Court of Appeals
    2. 94 US District Court
    3. 92 US Bankruptcy Court
    
    """
    
    def __init__(self):
        pass
    
    def US_court_of_appeals_dict(self):
        
        US_court_of_appeals_dict = {'United States Court of Appeals for the First Circuit':'https://www.ca1.uscourts.gov/',
                            'United States Court of Appeals for the Second Circuit':'https://www.ca2.uscourts.gov/',
                            'United States Court of Appeals for the Third Circuit':'https://www.ca3.uscourts.gov/',
                            'United States Court of Appeals for the Fourth Circuit':'https://www.ca4.uscourts.gov/',
                            'United States Court of Appeals for the Fifth Circuit':'https://www.ca5.uscourts.gov/',
                            'United States Court of Appeals for the Sixth Circuit':'https://www.ca6.uscourts.gov/',
                            'United States Court of Appeals for the Seventh Circuit':'https://www.ca7.uscourts.gov/',
                            'United States Court of Appeals for the Eighth Circuit':'https://www.ca8.uscourts.gov/',
                            'United States Court of Appeals for the Ninth Circuit':'https://www.ca9.uscourts.gov/',
                            'United States Court of Appeals for the Tenth Circuit':'https://www.ca10.uscourts.gov/',
                            'United States Court of Appeals for the Eleventh Circuit':'https://www.ca11.uscourts.gov/',
                            'United States Court of Appeals District of Columbia Circuit':'https://www.cadc.uscourts.gov/',
                            'United States Court of Appeals for the Federal Circuit':'https://cafc.uscourts.gov/'}
        return US_court_of_appeals_dict
    
    def US_bankruptcy_court_dict(self):
        US_bankruptcy_court_dict = {'United States Bankruptcy Court for the Middle District of Alabama':'https://www.almb.uscourts.gov/',
                            'United States Bankruptcy Court for the Northern District of Alabama':'https://www.alnb.uscourts.gov/',
                            'United States Bankruptcy Court for the Southern District of Alabama':'https://www.alsb.uscourts.gov/',
                            'United States Bankruptcy Court for the District of Alaska':'https://www.akb.uscourts.gov/',
                            'United States Bankruptcy Court for the District of Arizona':'https://www.azb.uscourts.gov/',
                            'United States Bankruptcy Court for the Eastern District of Arkansas':'https://www.areb.uscourts.gov/',
                            'United States Bankruptcy Court for the Western District of Arkansas':'https://www.arwd.uscourts.gov/',
                            'United States Bankruptcy Court for the Central District of California':'https://www.cacb.uscourts.gov/',
                            'United States Bankruptcy Court for the Eastern District of California':'https://www.caeb.uscourts.gov/',
                            'United States Bankruptcy Court for the Northern District of California':'https://www.canb.uscourts.gov/',
                         'United States Bankruptcy Court for the Southern District of California':'https://www.casb.uscourts.gov/',
                         'United States Bankruptcy Court for the District of Colorado':'https://www.cob.uscourts.gov/',
                         'United States Bankruptcy Court for the District of Connecticut':'https://www.ctb.uscourts.gov/',
                         'United States Bankruptcy Court for the District of Delaware':'https://www.deb.uscourts.gov/',
                         'United States Bankruptcy Court for the District of Columbia':'https://www.dcb.uscourts.gov/',
                         'United States Bankruptcy Court for the Northern District of Florida':'https://www.flnb.uscourts.gov/',
                         'United States Bankruptcy Court for the Middle District of Florida':'http://www.flmb.uscourts.gov/',
                         'United States Bankruptcy Court for the Southern District of Florida':'https://www.flsb.uscourts.gov/',
                         'United States Bankruptcy Court for the Northern District of Georgia':'https://www.ganb.uscourts.gov/',
                         'United States Bankruptcy Court for the Middle District of Georgia':'http://www.gamb.uscourts.gov/',
                         'United States Bankruptcy Court for the Southern District of Georgia':'https://www.gasb.uscourts.gov/',
                         'District Court of Guam':'https://www.gud.uscourts.gov/',
                         'United States Bankruptcy Court for the District of Hawaii':'https://www.hib.uscourts.gov/',
                         'United States Bankruptcy Court for the District of Idaho':'https://www.id.uscourts.gov/',
                         'United States Bankruptcy Court for the Northern District of Illinois':'https://www.ilnb.uscourts.gov/',
                         'United States Bankruptcy Court for the Central District of Illinois':'https://www.ilcb.uscourts.gov/',
                         'United States Bankruptcy Court for the Southern District of Illinois':'http://www.ilsb.uscourts.gov/',
                         'United States Bankruptcy Court for the Northern District of Indiana':'https://www.innb.uscourts.gov/',
                         'United States Bankruptcy Court for the Southern District of Indiana':'https://www.insb.uscourts.gov/',
                         'United States Bankruptcy Court for the Northern District of Iowa':'https://www.ianb.uscourts.gov/',
                         'United States Bankruptcy Court for the Southern District of Iowa':'https://www.iasb.uscourts.gov/',
                         'United States Bankruptcy Court for the District of Kansas':'https://www.ksb.uscourts.gov/',
                         'United States Bankruptcy Court for the Eastern District of Kentucky':'https://www.kyeb.uscourts.gov/',
                         'United States Bankruptcy Court for the Western District of Kentucky':'http://www.kywb.uscourts.gov/',
                         'United States Bankruptcy Court for the Eastern District of Louisiana':'https://www.laeb.uscourts.gov/',
                         'United States Bankruptcy Court for the Middle District of Louisiana':'https://www.lamb.uscourts.gov/',
                         'United States Bankruptcy Court for the Western District of Louisiana':'https://www.lawb.uscourts.gov/',
                         'United States Bankruptcy Court for the District of Maine':'https://www.meb.uscourts.gov/',
                         'United States Bankruptcy Court for the District of Maryland':'https://www.mdb.uscourts.gov/',
                         'United States Bankruptcy Court for the District of Massachusetts':'http://www.mab.uscourts.gov/',
                         'United States Bankruptcy Court for the Eastern District of Michigan':'http://www.mieb.uscourts.gov/',
                         'United States Bankruptcy Court for the Western District of Michigan':'https://www.miwb.uscourts.gov/',
                         'United States Bankruptcy Court for the District of Minnesota':'https://www.mnb.uscourts.gov/',
                         'United States Bankruptcy Court for the Northern District of Mississippi':'https://www.msnb.uscourts.gov/',
                         'United States Bankruptcy Court for the Southern District of Mississippi':'https://www.mssb.uscourts.gov/',
                         'United States Bankruptcy Court for the Eastern District of Missouri':'https://www.moeb.uscourts.gov/',
                         'United States Bankruptcy Court for the Western District of Missouri':'https://www.mow.uscourts.gov/',
                         'United States Bankruptcy Court for the District of Montana':'https://www.mtb.uscourts.gov/',
                         'United States Bankruptcy Court for the District of Nebraska':'https://www.neb.uscourts.gov/',
                         'United States Bankruptcy Court for the District of Nevada':'https://www.nvb.uscourts.gov/',
                         'United States Bankruptcy Court for the District of New Hampshire':'https://www.nhb.uscourts.gov/',
                         'United States Bankruptcy Court for the District of New Jersey':'http://www.njb.uscourts.gov/',
                         'United States Bankruptcy Court for the District of New Mexico':'https://www.nmb.uscourts.gov/',
                         'United States Bankruptcy Court for the Eastern District of New York':'https://www.nyeb.uscourts.gov/',
                         'United States Bankruptcy Court for the Northern District of New York':'https://www.nynb.uscourts.gov/',
                         'United States Bankruptcy Court for the Southern District of New York':'http://www.nysb.uscourts.gov/',
                         'United States Bankruptcy Court for the Western District of New York':'http://www.nywb.uscourts.gov/',
                         'United States Bankruptcy Court for the Eastern District of North Carolina':'https://www.nceb.uscourts.gov/',
                         'United States Bankruptcy Court for the Middle District of North Carolina':'https://www.ncmb.uscourts.gov/',
                         'United States Bankruptcy Court for the Western District of North Carolina':'https://www.ncwb.uscourts.gov/',
                         'United States Bankruptcy Court for the District of North Dakota':'http://www.ndb.uscourts.gov/',
                         'United States Bankruptcy Court for the Northern District of Ohio':'http://www.ohnb.uscourts.gov/',
                         'United States Bankruptcy Court for the Southern District of Ohio':"http://www.ohsb.uscourts.gov/",
                         'United States Bankruptcy Court for the Eastern District of Oklahoma':'https://www.okeb.uscourts.gov/',
                         'United States Bankruptcy Court for the Northern District of Oklahoma':'https://www.oknb.uscourts.gov/',
                         'United States Bankruptcy Court for the Western District of Oklahoma':'https://www.okwb.uscourts.gov/',
                         'United States Bankruptcy Court for the District of Oregon':'https://www.orb.uscourts.gov/',
                         'United States Bankruptcy Court for the Eastern District of Pennsylvania':'https://www.paeb.uscourts.gov/',
                         'United States Bankruptcy Court for the Middle District of Pennsylvania':'https://www.pamb.uscourts.gov/',
                         'United States Bankruptcy Court for the Western District of Pennsylvania':'https://www.pawb.uscourts.gov/',
                         'United States Bankruptcy Court for the District of Puerto Rico':'https://www.prb.uscourts.gov/',
                         'United States Bankruptcy Court for the District of Rhode Island':'https://www.rib.uscourts.gov/',
                         'United States Bankruptcy Court for the District of South Carolina':'https://www.scb.uscourts.gov/',
                         'United States Bankruptcy Court for the District of South Dakota':'https://www.sdb.uscourts.gov/',
                         'United States Bankruptcy Court for the Eastern District of Tennessee':'http://www.tneb.uscourts.gov/',
                         'United States Bankruptcy Court for the Middle District of Tennessee':'http://www.tnmb.uscourts.gov/',
                         'United States Bankruptcy Court for the Western District of Tennessee':'http://www.tnwb.uscourts.gov/',
                         'United States Bankruptcy Court for the Eastern District of Texas':'https://www.txeb.uscourts.gov/',
                         'United States Bankruptcy Court for the Northern District of Texas':'https://www.txnb.uscourts.gov/',
                         'United States Bankruptcy Court for the Southern District of Texas':'https://www.txs.uscourts.gov/',
                         'United States Bankruptcy Court for the Western District of Texas':'https://www.txwb.uscourts.gov/',
                         'United States Bankruptcy Court for the District of Utah':'https://www.utb.uscourts.gov/',
                         'United States Bankruptcy Court for the District of Vermont':'https://www.vtb.uscourts.gov/',
                         'United States Bankruptcy Court for the Eastern District of Virginia':'https://www.vaeb.uscourts.gov/',
                         'United States Bankruptcy Court for the Western District of Virginia':'https://www.vawb.uscourts.gov/',
                         'United States Bankruptcy Court for the Eastern District of Washington':'https://www.waeb.uscourts.gov/',
                         'United States Bankruptcy Court for the Western District of Washington':'https://www.wawb.uscourts.gov/',
                         'United States Bankruptcy Court for the Northern District of West Virginia':'https://www.wvnb.uscourts.gov/',
                         'United States Bankruptcy Court for the Southern District of West Virginia':'https://www.wvsb.uscourts.gov/',
                         'United States Bankruptcy Court for the Eastern District of Wisconsin':'https://www.wieb.uscourts.gov/',
                         'United States Bankruptcy Court for the Western District of Wisconsin':'https://www.wiwb.uscourts.gov/',
                         'United States Bankruptcy Court for the District of Wyoming':'https://www.wyb.uscourts.gov/'}
        return US_bankruptcy_court_dict
    
    def US_district_court_dict(self):
        US_district_court_dict = {'United States District Court for the Northern District of Alabama':'https://www.alnd.uscourts.gov/',
                         'United States District Court for the Middle District of Alabama':'https://www.almd.uscourts.gov/',
                         'United States District Court for the Southern District of Alabama':'https://www.alsd.uscourts.gov/',
                         'United States District Court for the District of Alaska':'https://www.akd.uscourts.gov/',
                         'United States District Court for the District of Arizona':'https://www.azd.uscourts.gov/',
                         'United States District Court for the Eastern District of Arkansas':'https://www.are.uscourts.gov/',
                         'United States District Court for the Western District of Arkansas':'https://www.arwd.uscourts.gov/',
                         'United States District Court for the Central District of California':'https://www.cacd.uscourts.gov/',
                         'United States District Court for the Eastern District of California':'https://www.caed.uscourts.gov/',
                         'United States District Court for the Northern District of California':'https://www.cand.uscourts.gov/',
                         'United States District Court for the Southern District of California':'https://www.casd.uscourts.gov/',
                         'United States District Court for the District of Colorado':'http://www.cod.uscourts.gov',
                         'United States District Court for the District of Connecticut':'https://www.ctd.uscourts.gov/',
                         'United States District Court for the District of Delaware':'https://www.ded.uscourts.gov/',
                         'United States District Court for the District of Columbia':"https://www.dcd.uscourts.gov/",
                         'United States District Court for the Northern District of Florida':'http://www.flnd.uscourts.gov/',
                         'United States District Court for the Middle District of Florida':"https://www.flmd.uscourts.gov/",
                         'United States District Court for the Southern District of Florida':'https://www.flsd.uscourts.gov/',
                         'United States District Court for the Northern District of Georgia':'http://www.gand.uscourts.gov/',
                         'United States District Court for the Middle District of Georgia':'https://www.gamd.uscourts.gov/',
                         'United States District Court for the Southern District of Georgia':'https://www.gasd.uscourts.gov/',
                         'District Court of Guam':'https://www.gud.uscourts.gov/',
                         'United States District Court for the District of Hawaii':'https://www.hid.uscourts.gov/',
                         'United States District Court for the District of Idaho':'https://www.id.uscourts.gov/',
                         'United States District Court for the Northern District of Illinois':"https://www.ilnd.uscourts.gov/",
                         'United States District Court for the Central District of Illinois':'https://www.ilcd.uscourts.gov/',
                         'United States District Court for the Southern District of Illinois':'https://www.ilsd.uscourts.gov/',
                         'United States District Court for the Northern District of Indiana':'https://www.innd.uscourts.gov/',
                         'United States District Court for the Southern District of Indiana':'https://www.insd.uscourts.gov/',
                         'United States District Court for the Northern District of Iowa':'https://www.iand.uscourts.gov/',
                         'United States District Court for the Southern District of Iowa':'https://www.iasd.uscourts.gov/',
                         'United States District Court for the District of Kansas':'https://ksd.uscourts.gov/',
                         'United States District Court for the Eastern District of Kentucky':'https://www.kyed.uscourts.gov/',
                         'United States District Court for the Western District of Kentucky':'https://www.kywd.uscourts.gov/',
                         'United States District Court for the Eastern District of Louisiana':'https://www.laed.uscourts.gov/',
                         'United States District Court for the Middle District of Louisiana':'https://www.lamd.uscourts.gov/',
                         'United States District Court for the Western District of Louisiana':'https://www.lawd.uscourts.gov/',
                         'United States District Court for the District of Maine':'https://www.med.uscourts.gov/',
                         'United States District Court for the District of Maryland':'https://www.mdd.uscourts.gov/',
                         'United States District Court for the District of Massachusetts':'https://www.mad.uscourts.gov/',
                         'United States District Court for the Eastern District of Michigan':'https://www.mied.uscourts.gov/',
                         'United States District Court for the Western District of Michigan':'https://www.miwd.uscourts.gov/',
                         'United States District Court for the District of Minnesota':'https://www.mnd.uscourts.gov/',
                         'United States District Court for the Northern District of Mississippi':'https://www.msnd.uscourts.gov/',
                         'United States District Court for the Southern District of Mississippi':'https://www.mssd.uscourts.gov/',
                         'United States District Court for the Eastern District of Missouri':'https://www.moed.uscourts.gov/',
                         'United States District Court for the Western District of Missouri':'https://www.mow.uscourts.gov/',
                         'United States District Court for the District of Montana':'https://www.mtd.uscourts.gov/',
                         'United States District Court for the District of Nebraska':'https://www.ned.uscourts.gov/',
                         'United States District Court for the District of Nevada':'https://www.nvd.uscourts.gov/',
                         'United States District Court for the District of New Hampshire':'https://www.nhd.uscourts.gov/',
                         'United States District Court for the District of New Jersey':'https://www.njd.uscourts.gov/',
                         'United States District Court for the District of New Mexico':'https://www.nmd.uscourts.gov/',
                         'United States District Court for the Eastern District of New York':'https://www.nyed.uscourts.gov/',
                         'United States District Court for the Northern District of New York':'https://www.nynd.uscourts.gov/',
                         'United States District Court for the Southern District of New York':'https://www.nysd.uscourts.gov/',
                         'United States District Court for the Western District of New York':'https://www.nywd.uscourts.gov/',
                         'United States District Court for the Eastern District of North Carolina':'https://www.nced.uscourts.gov/',
                         'United States District Court for the Middle District of North Carolina':'https://www.ncmd.uscourts.gov/',
                         'United States District Court for the Western District of North Carolina':'https://www.ncnd.uscourts.gov/',
                         'United States District Court for the District of North Dakota':'https://www.ndd.uscourts.gov/',
                         'District Court for the Northern Mariana Islands':'https://www.nmid.uscourts.gov/',
                         'United States District Court for the Northern District of Ohio':'https://www.ohnd.uscourts.gov/',
                         'United States District Court for the Southern District of Ohio':'https://www.ohsd.uscourts.gov/',
                         'United States District Court for the Eastern District of Oklahoma':'https://www.oked.uscourts.gov/',
                         'United States District Court for the Northern District of Oklahoma':'https://www.oknd.uscourts.gov/',
                         'United States District Court for the Western District of Oklahoma':'https://www.okwd.uscourts.gov/',
                         'United States District Court for the District of Oregon':'https://www.ord.uscourts.gov/',
                         'United States District Court for the Eastern District of Pennsylvania':'https://www.paed.uscourts.gov/',
                         'United States District Court for the Middle District of Pennsylvania':'https://www.pamd.uscourts.gov/',
                         'United States District Court for the Western District of Pennsylvania':'https://www.pawd.uscourts.gov/',
                         'United States District Court for the District of Puerto Rico':'https://www.prd.uscourts.gov/',
                         'United States District Court for the District of Rhode Island':'https://www.rid.uscourts.gov/',
                         'United States District Court for the District of South Carolina':'http://www.scd.uscourts.gov/',
                         'United States District Court for the District of South Dakota':'https://www.sdd.uscourts.gov/',
                         'United States District Court for the Eastern District of Tennessee':'https://www.tned.uscourts.gov/',
                         'United States District Court for the Middle District of Tennessee':'https://www.tnmd.uscourts.gov/',
                         'United States District Court for the Western District of Tennessee':'https://www.tnwd.uscourts.gov/',
                         'United States District Court for the Eastern District of Texas':'https://www.txed.uscourts.gov/',
                         'United States District Court for the Northern District of Texas':'https://www.txnd.uscourts.gov/',
                         'United States District Court for the Southern District of Texas':'https://www.txs.uscourts.gov/',
                         'United States District Court for the Western District of Texas':'https://www.txwd.uscourts.gov/',
                         'United States District Court for the District of Utah':'https://www.utd.uscourts.gov/',
                         'United States District Court for the District of Vermont':'https://www.vtd.uscourts.gov/',
                         'District Court of the Virgin Islands':'https://www.vid.uscourts.gov/',
                         'United States District Court for the Eastern District of Virginia':'https://www.vaed.uscourts.gov/',
                         'United States District Court for the Western District of Virginia':'http://www.vawd.uscourts.gov/',
                         'United States District Court for the Eastern District of Washington':'https://www.waed.uscourts.gov/',
                         'United States District Court for the Western District of Washington':'https://www.wawd.uscourts.gov/',
                         'United States District Court for the Northern District of West Virginia':'https://www.wvnd.uscourts.gov/',
                         'United States District Court for the Southern District of West Virginia':'https://www.wvsd.uscourts.gov/',
                         'United States District Court for the Eastern District of Wisconsin':'https://www.wied.uscourts.gov/',
                         'United States District Court for the Western District of Wisconsin':'https://www.wiwd.uscourts.gov/',
                         'United States District Court for the District of Wyoming':'https://www.wyd.uscourts.gov/'}
        return US_district_court_dict

